# Generated by Django 3.1 on 2020-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Dateofbirth', models.DateTimeField(default=0)),
                ('occupation', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=0)),
                ('contact', models.IntegerField(default=0)),
                ('Fathername', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
            ],
        ),
    ]
